import { CreateRecipeRequest } from '../types/CreateRecipe'

export const recipes: CreateRecipeRequest['recipe'][] = [
    {
        name: 'Chips de morena con pisto murciano',
        category: 'Entrante',
        allergens: ['fish', 'gluten'],
        productionTime: '1 hora',
        pvp: 15.0,
        servingsPerProduction: 4,
        priceVariation: 2.5,
        inMenu: true,
        ingredients: [
            { id: 'new', name: 'Morena fresca', quantityPerProduction: 0.25, unit: 'kg', pricePerUnit: 18 },
            { id: 'new', name: 'Tomate raf maduro', quantityPerProduction: 0.35, unit: 'kg', pricePerUnit: 3 },
            { id: 'new', name: 'Pimiento verde italiano', quantityPerProduction: 0.12, unit: 'kg', pricePerUnit: 1.2 },
            { id: 'new', name: 'Cebolla dulce', quantityPerProduction: 0.12, unit: 'kg', pricePerUnit: 1.5 },
            {
                id: 'new',
                name: 'Aceite de oliva virgen extra premium',
                quantityPerProduction: 0.06,
                unit: 'l',
                pricePerUnit: 10,
            },
            {
                id: 'new',
                name: 'Harina de trigo ecológica',
                quantityPerProduction: 0.05,
                unit: 'kg',
                pricePerUnit: 0.6,
            },
        ],
        preparation: {
            prePreparation: ['Limpiar y filetear cuidadosamente la morena', 'Picar verduras en brunoise muy fina'],
            preparation: [
                'Enharinar ligeramente los filetes de morena y freír hasta lograr textura crujiente y dorada',
                'Cocinar lentamente las verduras en aceite de oliva premium hasta obtener un pisto suave y aromático',
                'Presentar en plato elegante con el pisto de base y chips de morena encima',
            ],
            conservation: ['Servir inmediatamente después de su elaboración'],
        },
    },
    {
        name: 'Tartar de tomate con merengue de aquafaba',
        category: 'Vegetariano',
        allergens: [],
        productionTime: '45 min',
        pvp: 13.0,
        servingsPerProduction: 4,
        priceVariation: 1.8,
        inMenu: true,
        ingredients: [
            {
                id: 'new',
                name: 'Tomate ecológico variedad antigua',
                quantityPerProduction: 0.4,
                unit: 'kg',
                pricePerUnit: 4,
            },
            { id: 'new', name: 'Aquafaba', quantityPerProduction: 0.12, unit: 'l', pricePerUnit: 0.8 },
            {
                id: 'new',
                name: 'Aceite de oliva virgen extra premium',
                quantityPerProduction: 0.025,
                unit: 'l',
                pricePerUnit: 10,
            },
            { id: 'new', name: 'Microbrotes de albahaca', quantityPerProduction: 0.015, unit: 'kg', pricePerUnit: 3 },
        ],
        preparation: {
            prePreparation: [
                'Seleccionar y picar tomates en cubos muy pequeños',
                'Montar aquafaba con precisión a punto de nieve',
            ],
            preparation: [
                'Aliñar delicadamente los tomates con aceite de oliva premium y sal en escamas',
                'Formar el tartar en el centro del plato',
                'Cubrir suavemente con merengue de aquafaba',
                'Decorar artísticamente con microbrotes de albahaca',
            ],
            conservation: ['Mantener refrigerado y servir inmediatamente'],
        },
    },
    {
        name: 'Estofado de setas con yema de huevo campero y judía verde',
        category: 'Principal',
        allergens: ['eggs'],
        productionTime: '1 hora 30 min',
        pvp: 22.0,
        servingsPerProduction: 4,
        priceVariation: 3.0,
        inMenu: true,
        ingredients: [
            {
                id: 'new',
                name: 'Setas silvestres mixtas de temporada',
                quantityPerProduction: 0.45,
                unit: 'kg',
                pricePerUnit: 15,
            },
            {
                id: 'new',
                name: 'Yema de huevo campero ecológico',
                quantityPerProduction: 4,
                unit: 'kg',
                pricePerUnit: 0.7,
            },
            {
                id: 'new',
                name: 'Judías verdes frescas ecológicas',
                quantityPerProduction: 0.2,
                unit: 'kg',
                pricePerUnit: 4,
            },
            {
                id: 'new',
                name: 'Caldo de verduras concentrado casero',
                quantityPerProduction: 0.35,
                unit: 'l',
                pricePerUnit: 2,
            },
            { id: 'new', name: 'Ajo negro', quantityPerProduction: 0.015, unit: 'kg', pricePerUnit: 1 },
            {
                id: 'new',
                name: 'Aceite de oliva virgen extra premium',
                quantityPerProduction: 0.04,
                unit: 'l',
                pricePerUnit: 10,
            },
        ],
        preparation: {
            prePreparation: [
                'Seleccionar y limpiar minuciosamente setas silvestres',
                'Cortar judías verdes con precisión en juliana',
            ],
            preparation: [
                'Saltear setas con ajo negro en aceite premium',
                'Añadir caldo concentrado y estofar lentamente hasta lograr textura y sabor intensos',
                'Escaldar brevemente judías verdes para mantener su frescura',
                'Servir las setas en un plato hondo con la yema de huevo campero ligeramente templada y judías verdes dispuestas con elegancia alrededor',
            ],
            conservation: ['Consumir recién hecho y caliente'],
        },
    },
]
